### ISSUE TITLE
Handle filtering Originals/Offers (name pending) data

### ISSUE THREAD

**Issue by nicosantangelo** [decentraland/marketplace#332]
Manage the new filter in the URL and clean the other filters when it changes. Use the new data provided by the server.

We also need to: 
- Move it to it's actual location in the code (`ItemBrowse` perhaps?) as it's setup just as an example right now
- Internationalize it (I18n)

**Comment by nachomazzara** [comment]
@davecarrDCL @schallock  we need to show two options in the marketplace to filter by `primary sales` and `secondary sales`. What names do you suggest for each? 

Right now we have:
- `originals` for primary
- `offers` for secondary

![Screen Shot 2021-06-09 at 10.50.16.png](https://images.zenhubusercontent.com/5e7388701e944359f1d16293/9f1a1453-ee59-431c-acbc-b7ef7c268969)

**Comment by davecarrDCL** [comment]
Hey Nacho,
For me, I would keep it simple and stick with *Primary* and *Secondary*. If
you use *Originals* then you are just repeating it in the description
underneath and it's not necessary. So I suggest:

*Primary*
New and original creations by users

*Secondary*
Pre-owned items being resold

The reason I use 'pre-owned' is because I wasn't sure if Collectibles
covered all things being resold in the Marketplace.

Let me know if you're happy with these or if you need anything else.

Cheers,
Dave
