### ISSUE TITLE
`npm run sanity-check` without BATCH_SIZE gets stuck

### ISSUE THREAD

**Issue by cazala** [decentraland/marketplace#498]
```
➜  marketplace git:(feat/updateop) npm run sanity-check -- --self-heal
[main] Batch size configurable via BATCH_SIZE
[main] Connecting to database
[main] Connecting to Ethereum node
[main] Starting CLI
[Sanity] [1/3]: Running Parcel
[asyncBatch] 45300.5 as batch size, got undefined
```

i dunno why `[asyncBatch] 45300.5 as batch size, got undefined` but it stays there forever.

It only works as `BATCH_SIZE=XXX npm run sanity-check -- --self-heal`

We need a default value or make it throw if not provided or something

**Comment by NicoSantangelo** [comment]
The default is half the total size! that's why you see `45300.5`. It's a generic approach intended for smaller arrays.

I'll add a more sensible default (max between half the total size and 100) and I'll replace `[asyncBatch] 45300.5 as batch size, got undefined` with `[asyncBatch] Defaulting to 100 as batch size, got undefined`
