### ISSUE TITLE
Webpack is not minifying files for prod

### ISSUE THREAD

**Issue by hernimen** [decentraland/marketplace#908]
## 🎉 Description

- Webpack not minifying files for production env.

* [x] 🐛 This is a bug report.
* [ ] 📈 This is a feature request.

## 📝 Details

Describe the problem you have been experiencing in more detail. Include as much information as you think is relevant. Keep in mind that transactions can fail for many reasons; context is key here. Links to tx, screenshots are welcome.
Remember to not share sensible information
Issue: https://imgur.com/a/ZIz79ee
## 🔢 Steps To Reproduce Issue [ Good To Have ]

Please remember that with baby steps it's easier to reproduce the bug and it's much faster to fix it.

```
- Step 1
  Open your web browser dev tools
- Step 2
  Go to source tab
- Step 3
 Many files are not being minified. Look like Webpack in prod it's not working as it should.

...
```

**Comment by abarmat** [comment]
Hey, thank you for the report.

I've checked the app and we are sending both the JS and CSS minified, you can see that from the `Network tab`.
What you see in the source tab as separated files is due to a sourceMapping being sent over the wire so the browser knows how to read the bundled files.

<img width="966" alt="minified" src="https://user-images.githubusercontent.com/140773/56571636-a8661f00-65bd-11e9-9424-d04a86ddb0d7.png">
